-- =====================================================================
-- XJBR — Controle de Custos de Obra (MULTI-PARCEIRO)
-- Schema do banco (PostgreSQL / Supabase)
-- ---------------------------------------------------------------------
-- Um único banco guarda TODOS os parceiros (mpi, construtorax, …),
-- com dados ISOLADOS por parceiro através de RLS.
-- Como usar: Supabase → SQL Editor → New query → cole tudo → Run.
-- (Seguro rodar de novo: usa "if not exists" / "on conflict".)
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- PERFIS  (usuário -> papel + parceiro)
--   tenant = a "chave" do parceiro usada na URL (ex.: 'mpi')
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  role       text not null check (role in ('financeiro','viewer','dev')),
  tenant     text not null,   -- para 'dev' pode ser qualquer valor (ele vê todos)
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------
-- OBRAS  (as casas / imóveis) — por parceiro
-- ---------------------------------------------------------------------
create table if not exists public.obras (
  id         uuid primary key default gen_random_uuid(),
  tenant     text not null,
  nome       text not null,
  created_at timestamptz default now()
);
create index if not exists idx_obras_tenant on public.obras (tenant);

-- ---------------------------------------------------------------------
-- LANÇAMENTOS  (as despesas) — por parceiro
--   fonte = texto livre (cada parceiro tem suas duas fontes pagadoras)
-- ---------------------------------------------------------------------
create table if not exists public.lancamentos (
  id         uuid primary key default gen_random_uuid(),
  tenant     text not null,
  numero     bigint generated by default as identity,  -- código sequencial (#001…)
  data       date,
  fonte      text,
  cc         text check (cc in ('OBRA','MAO_DE_OBRA','DOCUMENTACAO','')) default '',
  fornecedor text default '',
  referencia text default '',
  valor      numeric(14,2) not null default 0,
  casas      uuid[] not null default '{}',
  arquivos   jsonb  not null default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_lanc_tenant on public.lancamentos (tenant);
create index if not exists idx_lanc_casas  on public.lancamentos using gin (casas);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_lanc_touch on public.lancamentos;
create trigger trg_lanc_touch before update on public.lancamentos
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Funções: papel e parceiro do usuário logado (usadas pelas regras RLS)
-- ---------------------------------------------------------------------
create or replace function public.user_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;
create or replace function public.user_tenant()
returns text language sql stable security definer set search_path = public as $$
  select tenant from public.profiles where id = auth.uid();
$$;

-- =====================================================================
-- SEGURANÇA (RLS)
--   Cada usuário só LÊ/ESCREVE dados do SEU parceiro (tenant).
--   Só 'financeiro' escreve.
-- =====================================================================
alter table public.profiles    enable row level security;
alter table public.obras       enable row level security;
alter table public.lancamentos enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
  for select to authenticated using (id = auth.uid());

-- OBRAS  (dev vê/edita todos os parceiros)
drop policy if exists obras_read on public.obras;
create policy obras_read on public.obras
  for select to authenticated
  using (tenant = public.user_tenant() or public.user_role() = 'dev');
drop policy if exists obras_write on public.obras;
create policy obras_write on public.obras
  for all to authenticated
  using ((tenant = public.user_tenant() and public.user_role() = 'financeiro') or public.user_role() = 'dev')
  with check ((tenant = public.user_tenant() and public.user_role() = 'financeiro') or public.user_role() = 'dev');

-- LANÇAMENTOS  (dev vê/edita todos os parceiros)
drop policy if exists lanc_read on public.lancamentos;
create policy lanc_read on public.lancamentos
  for select to authenticated
  using (tenant = public.user_tenant() or public.user_role() = 'dev');
drop policy if exists lanc_write on public.lancamentos;
create policy lanc_write on public.lancamentos
  for all to authenticated
  using ((tenant = public.user_tenant() and public.user_role() = 'financeiro') or public.user_role() = 'dev')
  with check ((tenant = public.user_tenant() and public.user_role() = 'financeiro') or public.user_role() = 'dev');

-- =====================================================================
-- STORAGE — bucket privado; arquivos isolados por parceiro (pasta = tenant)
-- =====================================================================
insert into storage.buckets (id, name, public)
values ('comprovantes', 'comprovantes', false)
on conflict (id) do nothing;

drop policy if exists comprovantes_read on storage.objects;
create policy comprovantes_read on storage.objects
  for select to authenticated
  using (bucket_id = 'comprovantes' and ((storage.foldername(name))[1] = public.user_tenant() or public.user_role() = 'dev'));

drop policy if exists comprovantes_write on storage.objects;
create policy comprovantes_write on storage.objects
  for insert to authenticated
  with check (bucket_id = 'comprovantes' and (((storage.foldername(name))[1] = public.user_tenant() and public.user_role() = 'financeiro') or public.user_role() = 'dev'));

drop policy if exists comprovantes_delete on storage.objects;
create policy comprovantes_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'comprovantes' and (((storage.foldername(name))[1] = public.user_tenant() and public.user_role() = 'financeiro') or public.user_role() = 'dev'));

-- =====================================================================
-- TENANT_SETTINGS — configuração e credenciais por parceiro
--   RLS habilitado e SEM policies: só o backend (service_role), via
--   funções serverless em /api, pode ler/escrever esta tabela.
--   Os clientes (navegador) nunca têm acesso direto a ela.
-- =====================================================================
create table if not exists public.tenant_settings (
  tenant                    text primary key,
  nome                      text,
  fontes                    text[],
  logo                      jsonb,
  pass_financeiro_hash      text,
  pass_viewer_hash          text,
  internal_pass_financeiro  text,
  internal_pass_viewer      text,
  internal_pass_dev         text,
  financeiro_user_id        uuid,
  viewer_user_id            uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.tenant_settings enable row level security;

drop trigger if exists trg_tenant_settings_touch on public.tenant_settings;
create trigger trg_tenant_settings_touch before update on public.tenant_settings
  for each row execute function public.touch_updated_at();

-- =====================================================================
-- USUÁRIOS POR PARCEIRO
--   As contas de Authentication (financeiro@<tenant>.xjbr.local,
--   visualizador@<tenant>.xjbr.local, dev@xjbr.local), os registros em
--   public.profiles e as senhas (com hash) em public.tenant_settings
--   são criados/gerenciados automaticamente pelo backend:
--     • Primeira configuração: POST /api/admin/bootstrap (uma única vez)
--     • Novos parceiros / troca de senha: painel Admin (usuário dev),
--       que chama /api/admin/tenants
--   Não é necessário (e não deve ser feito) criar essas contas
--   manualmente pelo SQL Editor.
-- =====================================================================
